// Google Maps dark style tuned to DengueSat CIRO brand palette.
// Surfaces: #0B0F17 base, #141A26 land, #1A2536 elevations. Primary accent #107BFF.
export const DARK_MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#0B0F17' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#7A8BA6' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#0B0F17' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#1A2536' }] },
  { featureType: 'administrative.country', elementType: 'labels.text.fill', stylers: [{ color: '#A0AEC0' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#FFFFFF' }] },
  { featureType: 'administrative.neighborhood', elementType: 'labels.text.fill', stylers: [{ color: '#7A8BA6' }] },
  { featureType: 'landscape', elementType: 'geometry', stylers: [{ color: '#141A26' }] },
  { featureType: 'landscape.natural', elementType: 'geometry', stylers: [{ color: '#10141C' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.business', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.medical', elementType: 'geometry', stylers: [{ color: '#1A2536' }, { visibility: 'on' }] },
  { featureType: 'poi.medical', elementType: 'labels.text.fill', stylers: [{ color: '#FF8A00' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#0F1A18' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#1A2536' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#0B0F17' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#5A6B85' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#232D3F' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#2D394D' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#107BFF' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#06090F' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#3D4A60' }] },
];

// Light mode — clean, low-saturation, off-white land. Subtle blue accent on highways.
export const LIGHT_MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#F4F6FA' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#3D4A60' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#FFFFFF' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#DCE3EE' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#1A2536' }] },
  { featureType: 'administrative.neighborhood', elementType: 'labels.text.fill', stylers: [{ color: '#5A6B85' }] },
  { featureType: 'landscape', elementType: 'geometry', stylers: [{ color: '#EEF1F7' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.business', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.medical', elementType: 'geometry', stylers: [{ color: '#FFE8D6' }, { visibility: 'on' }] },
  { featureType: 'poi.medical', elementType: 'labels.text.fill', stylers: [{ color: '#FF8A00' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#E5EFE3' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#FFFFFF' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#DCE3EE' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#5A6B85' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#FFFFFF' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#DCEBFF' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#107BFF' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#D2E4F7' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#107BFF' }] },
];
